package domain

type PlayerStats struct {
	PassAttempts                   int `json:"pass_attempts"`
	PassCompletions                int `json:"pass_completions"`
	PassNetYards                   int `json:"pass_net_yards"`
	PassLong                       int `json:"pass_long"`
	PassTouchdowns                 int `json:"pass_touchdowns"`
	PassInterceptions              int `json:"pass_interceptions"`
	PassFumbles                    int `json:"pass_fumbles"`
	RushAttempts                   int `json:"rush_attempts"`
	RushNetYards                   int `json:"rush_net_yards"`
	RushLong                       int `json:"rush_long"`
	RushTouchdowns                 int `json:"rush_touchdowns"`
	RushLongTouchdowns             int `json:"rush_long_touchdowns"`
	ReceiveAttempts                int `json:"receive_attempts"`
	ReceiveCaught                  int `json:"receive_caught"`
	ReceiveYards                   int `json:"receive_yards"`
	ReceiveLong                    int `json:"receive_long"`
	ReceiveTouchdowns              int `json:"receive_touchdowns"`
	ReceiveLongTouchdowns          int `json:"receive_long_touchdowns"`
	ReceiveYardsAfterCatch         int `json:"receive_yards_after_catch"`
	ReceiveFumbles                 int `json:"receive_fumbles"`
	Punts                          int `json:"punts"`
	PuntYards                      int `json:"punt_yards"`
	PuntNetYards                   int `json:"punt_net_yards"`
	PuntLong                       int `json:"punt_long"`
	PuntSingles                    int `json:"punt_singles"`
	PuntsBlocked                   int `json:"punts_blocked"`
	PuntsIn10                      int `json:"punts_in_10"`
	PuntsIn20                      int `json:"punts_in_20"`
	PuntsReturned                  int `json:"punts_returned"`
	KickReturns                    int `json:"kick_returns"`
	KickReturnsYards               int `json:"kick_returns_yards"`
	KickReturnsTouchdowns          int `json:"kick_returns_touchdowns"`
	KickReturnsLong                int `json:"kick_returns_long"`
	KickReturnsTouchdownsLong      int `json:"kick_returns_touchdowns_long"`
	FieldGoalAttempts              int `json:"field_goal_attempts"`
	FieldGoalMade                  int `json:"field_goal_made"`
	FieldGoalMisses                int `json:"field_goal_misses"`
	FieldGoalYards                 int `json:"field_goal_yards"`
	FieldGoalSingles               int `json:"field_goal_singles"`
	FieldGoalLong                  int `json:"field_goal_long"`
	FieldGoalPoints                int `json:"field_goal_points"`
	FieldGoalReturns               int `json:"field_goal_returns"`
	FieldGoalReturnsYards          int `json:"field_goal_returns_yards"`
	FieldGoalReturnsTouchdowns     int `json:"field_goal_returns_touchdowns"`
	FieldGoalReturnsLong           int `json:"field_goal_returns_long"`
	FieldGoalReturnsTouchdownsLong int `json:"field_goal_returns_touchdowns_long"`
	PuntReturns                    int `json:"punt_returns"`
	PuntReturnsYards               int `json:"punt_returns_yards"`
	PuntReturnsTouchdowns          int `json:"punt_returns_touchdowns"`
	PuntReturnsLong                int `json:"punt_returns_long"`
	PuntReturnsTouchdownsLong      int `json:"punt_returns_touchdowns_long"`
	Kicks                          int `json:"kicks"`
	KickYards                      int `json:"kick_yards"`
	KicksNetYards                  int `json:"kicks_net_yards"`
	KicksLong                      int `json:"kicks_long"`
	KicksSingles                   int `json:"kicks_singles"`
	KicksOutOfEndZone              int `json:"kicks_out_of_end_zone"`
	KicksOnside                    int `json:"kicks_onside"`
	OnePointConvertsAttempts       int `json:"one_point_converts_attempts"`
	OnePointConvertsMade           int `json:"one_point_converts_made"`
	TwoPointConvertsMade           int `json:"two_point_converts_made"`
	TacklesTotal                   int `json:"tackles_total"`
	TacklesDefensive               int `json:"tackles_defensive"`
	TacklesSpecialTeams            int `json:"tackles_special_teams"`
	SacksQbMade                    int `json:"sacks_qb_made"`
	Interceptions                  int `json:"interceptions"`
	FumblesForced                  int `json:"fumbles_forced"`
	FumblesRecovered               int `json:"fumbles_recovered"`
	PassesKnockedDown              int `json:"passes_knocked_down"`
}

type TeamStats struct {
	TotalFirstDowns   int    `json:"total_first_downs"`
	Rushes            int    `json:"rushes"`
	RushYards         int    `json:"rush_yards"`
	RushTouchdowns    int    `json:"rush_touchdowns"`
	PassAttempts      int    `json:"pass_attempts"`
	PassCompletions   int    `json:"pass_completions"`
	PassGrossYards    int    `json:"pass_gross_yards"`
	PassTouchdowns    int    `json:"pass_touchdowns"`
	PassInterceptions int    `json:"pass_interceptions"`
	QbRating          string `json:"qb_rating"`
	SacksTaken        int    `json:"sacks_taken"`
	TotalGrossYards   int    `json:"total_gross_yards"`
	TimesFumbled      int    `json:"times_fumbled"`
	FumblesLost       int    `json:"fumbles_lost"`
	Turnovers         int    `json:"turnovers"`
	Penalties         int    `json:"penalties"`
	PenaltyYards      int    `json:"penalty_yards"`
}
